export const REWARD_CATEGORY = {
  VOUCHER: 0,
  MERCHANDISE: 1,
  BOOK: 2,
};

export const REWARD_CATEGORY_LABELS = {
  [REWARD_CATEGORY.VOUCHER]: "Voucher",
  [REWARD_CATEGORY.MERCHANDISE]: "Quà tặng",
  [REWARD_CATEGORY.BOOK]: "Sách"
};
