export const REWARD_CATEGORY = {
  VOUCHER: 0,
  MERCHANDISE: 1,
  BOOK: 2,
  ELECTRONICS: 3,
  AVATAR: 4,
  THEME: 5,
};

export const REWARD_CATEGORY_LABELS = {
  [REWARD_CATEGORY.VOUCHER]: "Voucher",
  [REWARD_CATEGORY.MERCHANDISE]: "Quà tặng",
  [REWARD_CATEGORY.BOOK]: "Sách",
  [REWARD_CATEGORY.ELECTRONICS]: "Điện tử",
  [REWARD_CATEGORY.AVATAR]: "Avatar",
  [REWARD_CATEGORY.THEME]: "Giao diện",
};
