export const REWARD_ACTION_TYPE = {
  LOGIN: 0,
  COMPLETE_PROFILE: 1,
  SUBMIT_ASSIGNMENT: 2,
  PARTICIPATE_EVENT: 3,
  COMMENT_POST: 4,
  RECEIVE_LIKE: 5,
  CREATE_POST: 6,
  CUSTOM: 99,
};

export const REWARD_ACTION_LABELS = {
  [REWARD_ACTION_TYPE.LOGIN]: "Đăng nhập",
  [REWARD_ACTION_TYPE.COMPLETE_PROFILE]: "Hoàn thành thông tin",
  [REWARD_ACTION_TYPE.SUBMIT_ASSIGNMENT]: "Nộp bài tập",
  [REWARD_ACTION_TYPE.PARTICIPATE_EVENT]: "Tham gia sự kiện",
  [REWARD_ACTION_TYPE.COMMENT_POST]: "Bình luận bài viết",
  [REWARD_ACTION_TYPE.RECEIVE_LIKE]: "Nhận lượt thích",
  [REWARD_ACTION_TYPE.CREATE_POST]: "Tạo bài viết",
  [REWARD_ACTION_TYPE.CUSTOM]: "Hành động tùy chỉnh",
};
